name: Tarball

on: [ push, pull_request, workflow_dispatch, ]

jobs:
  tarball:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.x
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn
          cache: yarn

      - name: Setup
        run: |
          chmod +x Setup.sh
          ./Setup.sh

      - name: Build
        run: yarn --emoji true pack

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Tarball
          # A file, directory or wildcard pattern that describes what to upload
          path: ./svelte-snowpack-full-*.tgz

  validate:
    runs-on: ubuntu-latest
    needs: [tarball]

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: Tarball
          # Destination path
          path: ./

      - name: Unball
        run: tar zvxf svelte-snowpack-full-*.tgz

      # TODO: #3 Validate Shape of Tarball
      - name: Verify Shape
        run: 'echo "TODO: VERIFY THE SHAPE OF THE TARBALL"'
